### ISSUE TITLE
Recommended method of replacing the main view controllers from the Navigation drawer

### ISSUE THREAD

**Issue by codedentwickler** [dopebase/swift-drawer-menu#1]
First of all, Thanks for this simple library.

 What is the recommended way of replacing the main view controller when the navigation is clicked

**Comment by mrcflorian** [comment]
Sorry for the late response, @codedentwickler . I've just added support for this in DrawerController. Just call drawerController.navigateTo(viewController: viewController), to navigate to whichever controller you want
